services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['app.console_command']

    EonX\EasyTest\:
        resource: '../src'
        exclude:
            - '../src/Stub/HttpClient/*'
            - '../src/HttpKernel/*'
            - '../src/InvalidDataMaker/*'
            - '../src/Coverage/DataTransferObjects/*'

    EonX\EasyTest\Console\EasyTestApplication:
        arguments:
            $commands: !tagged_iterator 'app.console_command'

    EonX\EasyTest\Coverage\Resolvers\CloverCoverageResolver:
        tags:
            - {name: 'app.easy_test.coverage_resolver', key: 'clover'}

    EonX\EasyTest\Coverage\Resolvers\TextCoverageResolver:
        tags:
            - {name: 'app.easy_test.coverage_resolver', key: 'txt'}

    EonX\EasyTest\Coverage\Locators\CoverageResolverLocator:
        arguments:
            - !tagged_locator {tag: 'app.easy_test.coverage_resolver', index_by: 'key'}
