name: PHP-CI
on: [push]
jobs:
    coding_standards:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
                script:
                    - check-ecs
                    - check-phpstan
                    - check-security
                    - check-tests
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo; composer install --prefer-dist --no-progress;

            -   name: '[CI] Check ${{ matrix.script }} [CI]'
                run: composer ${{ matrix.script }}

    monorepo:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.3' ]
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: eonx-com/actions-cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ matrix.php }}-comp-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ matrix.php }}-comp-

            -   run: composer global require hirak/prestissimo; composer install --prefer-dist --no-progress;

            -   name: '[CI] Check composer [CI]'
                run: composer validate --strict

            -   name: '[CI] Check monorepo [CI]'
                run: composer validate-repo
