name: PHP Versions

on: [push]

jobs:
    php_versions_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '7.2', '7.4' ] # 7.3 already done in split_tests
                package: # Contains only package not requiring eonoepay externals package
                    - EasyApiToken
                    - EasyAsync
                    - EasyCore
                    - EasyDecision
                    - EasyPagination
                    - EasyPipeline
                    - EasyPsr7Factory
                    - EasyRepository
                    - EasySecurity

        name: ${{ matrix.package }} - PHP${{ matrix.php }}

        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --prefer-dist --no-progress # Install with stable php version
            -   run: vendor/bin/monorepo-builder localize-composer-paths

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: cd packages/${{ matrix.package }}; composer update --prefer-dist --no-progress
            -   run: cd packages/${{ matrix.package }}; vendor/bin/phpunit tests
